[project]
name = "fastapi-app"
version = "0.1.0"
description = "FastAPI project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.41",
    "boto3-stubs[bedrock-runtime]>=1.38.41",
    "fastapi[standard]>=0.115.13",
    "python-dotenv>=1.1.0",
]
