services:
  frontend_nextjs:
    build:
      context: ./frontend/nextjs-app
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: './frontend/nextjs-app'
        target: '/app/nextjs-app'
  backend_fastapi:
    build:
      context: ./backend/fastapi_app
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - type: bind
        source: './backend/fastapi_app'
        target: '/fastapi_app'
      - type: bind
        source: '/home/hiro/.aws/config'
        target: '/root/.aws/config'
        read_only: true
