
-- API プロバイダーテーブル
create table public.api_providers (
  id   integer generated by default as identity primary key, -- AUTO INCREMENT
  name text    not null unique                           -- 表示名
);

alter table public.api_providers enable row level security;

create policy "read_all_users"
  on public.api_providers
  for select
  to authenticated
  using (true);

-- ユーザーの API キー設定を保存するテーブル
create table public.api_key_settings (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  api_provider integer default null references public.api_providers(id) on delete set null, -- API プロバイダーID
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.api_key_settings enable row level security;

-- 読み
create policy "read_own"
  on public.api_key_settings
  for select
  to authenticated
  using ( (select auth.uid()) = user_id );

-- 書き
create policy "write_own"
  on public.api_key_settings
  for insert
  to authenticated
  with check ( (select auth.uid()) = user_id );

-- 更新
create policy "update_own"
  on public.api_key_settings
  for update
  to authenticated
  using ( (select auth.uid()) = user_id )
  with check ( (select auth.uid()) = user_id );
